####################################################################
# Install/Setup FirewallD
####################################################################
- name: Install/Setup FireallD
  yum:
    name: firewalld
    state: latest
- firewalld:
    service: ssh
    permanent: true
    state: enabled
- firewalld:
    service: https
    permanent: true
    state: enabled
- firewalld:
    service: http
    permanent: true
    state: enabled
- firewalld:
    port: 5044/tcp
    permanent: true
    state: enabled
- service:
    name: firewalld
    state: restarted
    enabled: yes
